/**
 * This file was generated by running: npm run codegen
 * Do not edit this file as it will be regenerated by codegen.
 *
 * @generated SignedSource<<8aa2b9f1e3c4a5d4b2e1f8c9d0a7b6e5>>
 */

#include "pch.h"
#include "NativeDeviceAISpec.h"

namespace facebook::react {

static jsi::Value __hostFunction_NativeDeviceAISpecJSI_getDeviceInfo(jsi::Runtime& rt, TurboModule& turboModule, const jsi::Value* args, size_t count) {
  return static_cast<NativeDeviceAISpecJSI*>(&turboModule)->getDeviceInfo(rt);
}

static jsi::Value __hostFunction_NativeDeviceAISpecJSI_getWindowsSystemInfo(jsi::Runtime& rt, TurboModule& turboModule, const jsi::Value* args, size_t count) {
  return static_cast<NativeDeviceAISpecJSI*>(&turboModule)->getWindowsSystemInfo(rt);
}

static jsi::Value __hostFunction_NativeDeviceAISpecJSI_isNativeModuleAvailable(jsi::Runtime& rt, TurboModule& turboModule, const jsi::Value* args, size_t count) {
  return static_cast<NativeDeviceAISpecJSI*>(&turboModule)->isNativeModuleAvailable(rt);
}

static jsi::Value __hostFunction_NativeDeviceAISpecJSI_getSupportedFeatures(jsi::Runtime& rt, TurboModule& turboModule, const jsi::Value* args, size_t count) {
  return static_cast<NativeDeviceAISpecJSI*>(&turboModule)->getSupportedFeatures(rt);
}

NativeDeviceAISpecJSI::NativeDeviceAISpecJSI(std::shared_ptr<CallInvoker> jsInvoker)
  : TurboModule("DeviceAI", jsInvoker) {
  
  methodMap_["getDeviceInfo"] = MethodMetadata {0, __hostFunction_NativeDeviceAISpecJSI_getDeviceInfo};
  methodMap_["getWindowsSystemInfo"] = MethodMetadata {0, __hostFunction_NativeDeviceAISpecJSI_getWindowsSystemInfo};
  methodMap_["isNativeModuleAvailable"] = MethodMetadata {0, __hostFunction_NativeDeviceAISpecJSI_isNativeModuleAvailable};
  methodMap_["getSupportedFeatures"] = MethodMetadata {0, __hostFunction_NativeDeviceAISpecJSI_getSupportedFeatures};
}

} // namespace facebook::react